services:
  app:
    container_name: licensei-backend
    build:
      context: .
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PG_HOST=db
  db:
    container_name: licensei-db
    image: postgres:16
    environment:
      - POSTGRES_DB=licensei
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      # TODO: Un-comment to allow data persisting
      #- ./data:/var/lib/postgresql/data
